local w = dofile(os.getenv("HOME") .. "/.config/conky/gruvbox-dark/widget-common.lua")
conky.config = w.card('storage')
conky.text = [[
${color1}${font Maple Mono NF CN:size=10}󰋊${font}  ${color5}${font Maple Mono NF CN:size=8}STORAGE${font}
${voffset 2}${color5}/${alignr}${color2}${fs_used /}${color5} / ${fs_size /}${offset 8}${color3}${fs_used_perc /}%
${voffset 2}${color4}${fs_bar /}
${voffset 5}${color5}nvme0n1${offset 8}${color2}󰛢 ${diskio_read nvme0n1}${alignr}${color2}󰛄 ${diskio_write nvme0n1}]]
