local w = dofile(os.getenv("HOME") .. "/.config/conky/gruvbox-dark/widget-common.lua")
conky.config = w.card('network')
conky.text = [[
${color1}${font Maple Mono NF CN:size=10}󰤨${font}  ${color5}${font Maple Mono NF CN:size=8}NETWORK${font}
${if_up wlan0}${voffset 2}${color5}ssid${alignr}${color2}${wireless_essid wlan0}
${color5}addr${alignr}${color2}${addr wlan0}
${color5}signal${offset 8}${color3}${wireless_link_qual_perc wlan0}%${alignr}${color4}${wireless_link_bar 4,150}
${voffset 4}${color2}󰇚 ${downspeed wlan0}${alignr}${color1}󰕒 ${upspeed wlan0}
${voffset 2}${color5}total${offset 8}${color2}${totaldown wlan0}${alignr}${color1}${totalup wlan0}${else}${voffset 2}${color7}wlan0 down${endif}${if_up tailscale0}
${color5}tailscale${alignr}${color9}${addr tailscale0}${endif}]]
