local w = dofile(os.getenv("HOME") .. "/.config/conky/gruvbox-dark/widget-common.lua")
conky.config = w.card('power')
conky.text = [[
${color1}${font Maple Mono NF CN:size=10}󰁹${font}  ${color5}${font Maple Mono NF CN:size=8}POWER${font}
${voffset 2}${color5}${battery_status BAT0}${alignr}${color3}${battery_percent BAT0}%
${voffset 2}${if_match ${battery_percent BAT0} < 20}${color7}${else}${color6}${endif}${battery_bar}
${voffset 5}${color5}remaining${alignr}${color2}${battery_time BAT0}]]
