local w = dofile(os.getenv("HOME") .. "/.config/conky/gruvbox-dark/widget-common.lua")
conky.config = w.card('cpu')
conky.text = [[
${color1}${font Maple Mono NF CN:size=10}󰻠${font}  ${color5}${font Maple Mono NF CN:size=8}PROCESSOR${font}
${voffset 2}${color3}${font Maple Mono NF CN:bold:size=15}${cpu cpu0}%${font}${color5}${offset 8}${voffset -4}${freq_g} GHz${alignr}${color3}${hwmon 3 temp 1}°C${voffset 4}
${voffset 2}${color5}${font Maple Mono NF CN:size=8}${execi 86400 grep -m1 'model name' /proc/cpuinfo | cut -d: -f2- | sed 's/^ *//; s/(R)//g; s/(TM)//g; s/ @.*//'}${font}
${voffset 4}${color5}1${color4}${cpubar cpu1 6,58}${offset 6}${color5}2${color4}${cpubar cpu2 6,58}${offset 6}${color5}3${color4}${cpubar cpu3 6,58}${offset 6}${color5}4${color4}${cpubar cpu4 6,58}
${color5}5${color4}${cpubar cpu5 6,58}${offset 6}${color5}6${color4}${cpubar cpu6 6,58}${offset 6}${color5}7${color4}${cpubar cpu7 6,58}${offset 6}${color5}8${color4}${cpubar cpu8 6,58}]]
