local w = dofile(os.getenv("HOME") .. "/.config/conky/gruvbox-dark/widget-common.lua")
conky.config = w.card('memory')
conky.text = [[
${color1}${font Maple Mono NF CN:size=10}󰍛${font}  ${color5}${font Maple Mono NF CN:size=8}MEMORY${font}
${voffset 2}${color2}${mem}${color5} / ${memmax}${alignr}${color3}${memperc}%
${voffset 2}${color4}${membar}
${voffset 5}${color5}swap${offset 8}${color2}${swap}${color5} / ${swapmax}${alignr}${color3}${swapperc}%
${voffset 2}${color9}${swapbar}]]
